---
- name: OpenVPN | Install | Set Distro/Version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    #- "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    #- "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    #- "../vars/default.yml"
  notify:
    - clear history

- import_tasks: packages.yml
- import_tasks: pki.yml
- import_tasks: openvpn.yml
- import_tasks: firewall.yml